export const bigProjects = [
  {
    id: 1,
    title: "EatAsYouWant",
    stacks: "NextJs - PostgreSQL - Prisma",
    status: "Projet personnel",
    desc: "Site de livraison de repas (gestion de commandes avec un admin board + authentification avec google)",
    img: "",
    link: "/",
    github: "https://github.com/jltp2c/eatAsyouWant",
    onBuild: true,
  },
  {
    id: 2,
    title: "HEAT",
    stacks: "React.JS - Node.JS - Express.JS - MongoDB",
    status: "Projet Hackaton IRONHACK : Prix 2ème position",
    desc: "Heat est un site web permettant d'enregistrer ses repas afin de suivre sa dépense calorique au quotidien. Une fois l'utilisateur connecté, Heat calcule le nombre de jours nécessaires à l'aboutissement de son objectif poids. L'interface permet un suivi sur plusieurs jours, sans limite de temps. Ce site web a été codé en 7 jours lors de la neuvième semaine de l'atelier de développement web IronHack.",
    img: "",
    github: "https://github.com/jltp2c/Heat-FrontEnd",
    link: "https://heatapp.netlify.app/",
    onBuild: false,
  },
  {
    id: 3,
    title: "Tekko",
    stacks: "HTML5/CSS3/Javascript ES6 - NodeJS - ExpressJS - Axios- HBS",
    status: "Projet Hackaton IRONHACK",
    desc: "Tekko permet aux Juniors d'accéder à des informations sur les salaires et à des évaluations anonymes de vrais employés. Les utilisateurs se connectent et peuvent ajouter, modifier, supprimer et accéder à leurs évaluations d'une manière très simple avec une interface conviviale (App full CRUD). Ce site web a été codé en 4 jours lors de la cinquième semaine de l'atelier de développement web IronHack",
    img: "",
    github: "https://github.com/jltp2c/Tekko",
    link: "https://github.com/jltp2c/Tekko",
    onBuild: false,
  },
  {
    id: 4,
    title: "La P'tite Cuisine",
    stacks: "React.JS - Sass - strapi",
    status: "Projet Freelance",
    desc: "Refonte from scratch : site web responsive avec React.JS / Strapi (gestion de client) + design pour 'la Ptite cuisine de Picpus'",
    img: "",
    github: "",
    link: "https://www.laptitecuisine.fr/",
    onBuild: false,
  },
];

export const smallProject = [
  {
    id: 1,
    title: "La P'tite Cuisine",
    stacks: "React.JS - Sass",
    status: "Projet Freelance",
    desc: "",
    img: "",
    github: "",
    link: "https://www.laptitecuisine.fr/",
    onBuild: false,
  },
];
